# Battlezone Sprite Table
# (Battlezone 98 Redux Version)

# NAME............................ MATERIAL........ ....U ....V ....W ....H REF.W REF.H FLAGS.....

# Status Display
"status_left"                      scrncut              0     0    63    84  1024  1024 0x00000000
"status_right"                     scrncut             63     0    53    24  1024  1024 0x00000000
"hull_bar"                         HUDcombi           636     0    69   140  1024  1024 0x00000000
"ammo_bar"                         HUDcombi           733     0    46   148  1024  1024 0x00000000
"shull_bar"                        HUDcombS           636     0    69   140  1024  1024 0x00000000
"sammo_bar"                        HUDcombS           733     0    46   148  1024  1024 0x00000000
"fhull_bar"                        HUDcombF           636     0    69   140  1024  1024 0x00000000
"fammo_bar"                        HUDcombF           733     0    46   148  1024  1024 0x00000000

# Scrap/Pilot Display
"scrap_panel"                      HUDcombi           660   960   180    64  1024  1024 0x00000000
"pilot_panel"                      HUDcombi           844   960   180    64  1024  1024 0x00000000
"sscrap_panel"                     HUDcombS           660   960   180    64  1024  1024 0x00000000
"spilot_panel"                     HUDcombS           844   960   180    64  1024  1024 0x00000000
"fscrap_panel"                     HUDcombF           660   960   180    64  1024  1024 0x00000000
"fpilot_panel"                     HUDcombF           844   960   180    64  1024  1024 0x00000000

# Radar Background
"radar6"                           radar6               0     0   223   112   223   112 0x00000000
"radar5"                           radar5               0     0   179    90   179    90 0x00000000
"radar4"                           radar4               0     0   139    70   139    70 0x00000000
"radar_left"                       radarhw              0     0   111   112   128   128 0x00000000
"radar_right"                      radarhw              0     0   112   112   128   128 0x00000000

# Radar Compass Directions
"compas_E"                         sprite_n            78     0     9     9   128   128 0x00000000
"compas_N"                         sprite_n            88     0     9     9   128   128 0x00000000
"compas_S"                         sprite_n            98     0     9     9   128   128 0x00000000
"compas_W"                         sprite_n           108     0     9     9   128   128 0x00000000

# Control Panel Key Icons
"key_ALT"                          sprite_n             0     0    15     9   128   128 0x00000000
"key_SHF"                          sprite_n            16     0    21     9   128   128 0x00000000
"key_SPC"                          sprite_n            38     0    23     9   128   128 0x00000000
"key_TAB"                          sprite_n            62     0    15     9   128   128 0x00000000
"key_0"                            sprite_n             0    10     9     9   128   128 0x00000000
"key_1"                            sprite_n            10    10     9     9   128   128 0x00000000
"key_2"                            sprite_n            20    10     9     9   128   128 0x00000000
"key_3"                            sprite_n            30    10     9     9   128   128 0x00000000
"key_4"                            sprite_n            40    10     9     9   128   128 0x00000000
"key_5"                            sprite_n            50    10     9     9   128   128 0x00000000
"key_6"                            sprite_n            60    10     9     9   128   128 0x00000000
"key_7"                            sprite_n            70    10     9     9   128   128 0x00000000
"key_8"                            sprite_n            80    10     9     9   128   128 0x00000000
"key_9"                            sprite_n            90    10     9     9   128   128 0x00000000
"key_F1"                           sprite_n             0    20    11     9   128   128 0x00000000
"key_F2"                           sprite_n            12    20    11     9   128   128 0x00000000
"key_F3"                           sprite_n            24    20    11     9   128   128 0x00000000
"key_F4"                           sprite_n            36    20    11     9   128   128 0x00000000
"key_F5"                           sprite_n            48    20    11     9   128   128 0x00000000
"key_F6"                           sprite_n            60    20    11     9   128   128 0x00000000
"key_F7"                           sprite_n            72    20    11     9   128   128 0x00000000
"key_F8"                           sprite_n            84    20    11     9   128   128 0x00000000
"key_F9"                           sprite_n            96    20    11     9   128   128 0x00000000

# Radar Light Unit Type Icons
"circ_O"                           sprite_n             0    30     7     7   128   128 0x00000000
"circ_D"                           sprite_n             8    30     7     7   128   128 0x00000000
"circ_U"                           sprite_n            16    30     7     7   128   128 0x00000000
"circ_B"                           sprite_n            24    30     7     7   128   128 0x00000000
"circ_R"                           sprite_n            32    30     7     7   128   128 0x00000000
"circ_A"                           sprite_n            40    30     7     7   128   128 0x00000000
"circ_F"                           sprite_n            48    30     7     7   128   128 0x00000000
"circ_C"                           sprite_n            56    30     7     7   128   128 0x00000000

# Radar Unit Number Icons (Light)
"circ_0"                           sprite_n             0    38     7     7   128   128 0x00000000
"circ_1"                           sprite_n             8    38     7     7   128   128 0x00000000
"circ_2"                           sprite_n            16    38     7     7   128   128 0x00000000
"circ_3"                           sprite_n            24    38     7     7   128   128 0x00000000
"circ_4"                           sprite_n            32    38     7     7   128   128 0x00000000
"circ_5"                           sprite_n            40    38     7     7   128   128 0x00000000
"circ_6"                           sprite_n            48    38     7     7   128   128 0x00000000
"circ_7"                           sprite_n            56    38     7     7   128   128 0x00000000
"circ_8"                           sprite_n            64    38     7     7   128   128 0x00000000
"circ_9"                           sprite_n            72    38     7     7   128   128 0x00000000

# Radar Unit Type Icons (Dark)
"dark_O"                           sprite_n             0    46     7     7   128   128 0x00000000
"dark_D"                           sprite_n             8    46     7     7   128   128 0x00000000
"dark_U"                           sprite_n            16    46     7     7   128   128 0x00000000
"dark_B"                           sprite_n            24    46     7     7   128   128 0x00000000
"dark_R"                           sprite_n            32    46     7     7   128   128 0x00000000
"dark_A"                           sprite_n            40    46     7     7   128   128 0x00000000
"dark_F"                           sprite_n            48    46     7     7   128   128 0x00000000
"dark_C"                           sprite_n            56    46     7     7   128   128 0x00000000

# Radar Unit Number Icons (Dark)
"dark_0"                           sprite_n             0    54     7     7   128   128 0x00000000
"dark_1"                           sprite_n             8    54     7     7   128   128 0x00000000
"dark_2"                           sprite_n            16    54     7     7   128   128 0x00000000
"dark_3"                           sprite_n            24    54     7     7   128   128 0x00000000
"dark_4"                           sprite_n            32    54     7     7   128   128 0x00000000
"dark_5"                           sprite_n            40    54     7     7   128   128 0x00000000
"dark_6"                           sprite_n            48    54     7     7   128   128 0x00000000
"dark_7"                           sprite_n            56    54     7     7   128   128 0x00000000
"dark_8"                           sprite_n            64    54     7     7   128   128 0x00000000
"dark_9"                           sprite_n            72    54     7     7   128   128 0x00000000

# Overview Cursors
"c_cross"                          sprite_n             0   112    16    16   128   128 0x00000000
"c_select"                         sprite_n            16   112    16    16   128   128 0x00000000
"c_move"                           sprite_n            32   112    16    16   128   128 0x00000000
"c_attack"                         sprite_n            48   112    16    16   128   128 0x00000000
"c_follow"                         sprite_n            64   112    16    16   128   128 0x00000000
"c_pickup"                         sprite_n            80   112    16    16   128   128 0x00000000
"c_dropof"                         sprite_n            96   112    16    16   128   128 0x00000000

# Weapon Type Indicators
"weapon_*"                         sprite_n           121     0     7     7   128   128 0x00000000
"weapon_C"                         sprite_n           121     8     7     7   128   128 0x00000000
"weapon_M"                         sprite_n           121    16     7     7   128   128 0x00000000
"weapon_R"                         sprite_n           121    24     7     7   128   128 0x00000000
"weapon_S"                         sprite_n           121    32     7     7   128   128 0x00000000

# Big Numbers (Green)
"bignum_G.0"                       bignum               0     0    16    24   128   128 0x00000000
"bignum_G.1"                       bignum              16     0    16    24   128   128 0x00000000
"bignum_G.2"                       bignum               0    24    16    24   128   128 0x00000000
"bignum_G.3"                       bignum              16    24    16    24   128   128 0x00000000
"bignum_G.4"                       bignum               0    48    16    24   128   128 0x00000000
"bignum_G.5"                       bignum              16    48    16    24   128   128 0x00000000
"bignum_G.6"                       bignum               0    72    16    24   128   128 0x00000000
"bignum_G.7"                       bignum              16    72    16    24   128   128 0x00000000
"bignum_G.8"                       bignum               0    96    16    24   128   128 0x00000000
"bignum_G.9"                       bignum              16    96    16    24   128   128 0x00000000
"bignum_G.."                       bignum               0   120     4     4   128   128 0x00000000

# Big Numbers (Yellow)
"bignum_Y.0"                       bignum              32     0    16    24   128   128 0x00000000
"bignum_Y.1"                       bignum              48     0    16    24   128   128 0x00000000
"bignum_Y.2"                       bignum              32    24    16    24   128   128 0x00000000
"bignum_Y.3"                       bignum              48    24    16    24   128   128 0x00000000
"bignum_Y.4"                       bignum              32    48    16    24   128   128 0x00000000
"bignum_Y.5"                       bignum              48    48    16    24   128   128 0x00000000
"bignum_Y.6"                       bignum              32    72    16    24   128   128 0x00000000
"bignum_Y.7"                       bignum              48    72    16    24   128   128 0x00000000
"bignum_Y.8"                       bignum              32    96    16    24   128   128 0x00000000
"bignum_Y.9"                       bignum              48    96    16    24   128   128 0x00000000
"bignum_Y.."                       bignum              32   120     4     4   128   128 0x00000000

# Big Numbers (Red)
"bignum_R.0"                       bignum              64     0    16    24   128   128 0x00000000
"bignum_R.1"                       bignum              80     0    16    24   128   128 0x00000000
"bignum_R.2"                       bignum              64    24    16    24   128   128 0x00000000
"bignum_R.3"                       bignum              80    24    16    24   128   128 0x00000000
"bignum_R.4"                       bignum              64    48    16    24   128   128 0x00000000
"bignum_R.5"                       bignum              80    48    16    24   128   128 0x00000000
"bignum_R.6"                       bignum              64    72    16    24   128   128 0x00000000
"bignum_R.7"                       bignum              80    72    16    24   128   128 0x00000000
"bignum_R.8"                       bignum              64    96    16    24   128   128 0x00000000
"bignum_R.9"                       bignum              80    96    16    24   128   128 0x00000000
"bignum_R.."                       bignum              64   120     4     4   128   128 0x00000000

# MAG Cannon Reticle
"gmaggun.0"                        gmaggun              0     0    64    32   128   128 0x00000000
"gmaggun.1"                        gmaggun              0    32    64    32   128   128 0x00000000
"gmaggun.2"                        gmaggun              0    64    64    32   128   128 0x00000000
"gmaggun.3"                        gmaggun              0    96    64    32   128   128 0x00000000
"gmaggun.4"                        gmaggun             64     0    64    32   128   128 0x00000000
"gmaggun.5"                        gmaggun             64    32    64    32   128   128 0x00000000
"gmaggun.6"                        gmaggun             64    64    64    32   128   128 0x00000000
"gmaggun.7"                        gmaggun             64    96    64    32   128   128 0x00000000

# Thermal Hornet Reticle
"ghornet.0"                        ghornet              0     0    64    32   128   128 0x00000000
"ghornet.1"                        ghornet              0    32    64    32   128   128 0x00000000
"ghornet.2"                        ghornet              0    64    64    32   128   128 0x00000000
"ghornet.3"                        ghornet              0    96    64    32   128   128 0x00000000
"ghornet.A"                        ghornet             64     0    64    64   128   128 0x00000000
"ghornet.B"                        ghornet             64    64    64    64   128   128 0x00000000

# Image Shadower Reticle
"gshadow.0"                        gshadow              0     0    64    32   128   128 0x00000000
"gshadow.1"                        gshadow              0    32    64    32   128   128 0x00000000
"gshadow.2"                        gshadow              0    64    64    32   128   128 0x00000000
"gshadow.3"                        gshadow              0    96    64    32   128   128 0x00000000
"gshadow.A"                        gshadow             64     0    64    64   128   128 0x00000000
"gshadow.B"                        gshadow             64    64    64    64   128   128 0x00000000

# Comet Cruise Reticle
"gcomet.0"                         gcomet               0     0    64    32   128   128 0x00000000
"gcomet.1"                         gcomet               0    32    64    32   128   128 0x00000000
"gcomet.2"                         gcomet               0    64    64    32   128   128 0x00000000
"gcomet.3"                         gcomet               0    96    64    32   128   128 0x00000000
"gcomet.A"                         gcomet              64     0    64    64   128   128 0x00000000
"gcomet.B"                         gcomet              64    64    64    64   128   128 0x00000000

# RED Field Reticle
"gredfld.0"                        reticle1             0     0    32    32   128   128 0x00000000
"gredfld.1"                        reticle1            32     0    32    32   128   128 0x00000000

# Phantom VIR Reticle
"gphantom.0"                       reticle1            64     0    32    32   128   128 0x00000000
"gphantom.1"                       reticle1            96     0    32    32   128   128 0x00000000

# Sandbag Reticle
"gsandbag"                         reticle1             0    32    32    32   128   128 0x00000000

# AT-Stabber Reticle
"gatstab"                          reticle1            32    32    32    32   128   128 0x00000000

# Thumper Reticle
"gquake"                           reticle1            64    32    32    32   128   128 0x00000000

# Minigun Reticle
"gminigun"                         reticle1            96    32    32    32   128   128 0x00000000

# TAG Cannon Reticle
"gtaggun.0"                        reticle1             0    64    32    32   128   128 0x00000000
"gtaggun.1"                        reticle1            32    64    32    32   128   128 0x00000000
"gtaggun.2"                        reticle1            64    64    32    32   128   128 0x00000000

# Nav Dropper Reticle
"gnavdrop"                         reticle1            96    64    32    32   128   128 0x00000000

# M-Curtain Reticle
"gmcurmin"                         reticle1             0    96    32    32   128   128 0x00000000

# MITS Mine Reticle
"gmitsmin"                         reticle1            32    96    32    32   128   128 0x00000000

# SITE Camera Reticle
"gsitecam.0"                       reticle1            64    96    32    32   128   128 0x00000000
"gsitecam.1"                       reticle1            96    96    32    32   128   128 0x00000000

# Bolt Buddy Reticle
"gbolt"                            reticle2             0     0    32    32   128   128 0x00000000

# Rocket Bomb Reticle
"grktbomb"                         reticle2            32     0    64    32   128   128 0x00000000

# MAS Grenade Reticle
"gmasgren"                         reticle2            96     0    32    32   128   128 0x00000000

# SP-Stabber Reticle
"gspstab"                          reticle2             0    32    32    32   128   128 0x00000000

# Flash Cannon Reticle
"gflashgn"                         reticle2            32    32    32    32   128   128 0x00000000

# Blast Cannon Reticle
"gblast"                           reticle2            64    32    32    32   128   128 0x00000000

# Proximity Mine Reticle
"gproxmin"                         reticle2             0    96    32    32   128   128 0x00000000

# Solar Flare Reticle
"gflare"                           reticle2            32    96    32    32   128   128 0x00000000

# Dot Reticle
"dot"                              reticle2           115    64     8     8   128   128 0x00000000

# Horizon Level Reticle
"sight"                            reticle2           115    73     5     5   128   128 0x00000000

# Standard Mortar Reticle
"gmortar"                          reticle2            96    32    32    13   128   128 0x00000000
"gmortar.L0"                       reticle2            96    47     9     5   128   128 0x00000000
"gmortar.R0"                       reticle2           119    47     9     5   128   128 0x00000000
"gmortar.L1"                       reticle2            96    54     6     5   128   128 0x00000000
"gmortar.R1"                       reticle2           122    54     6     5   128   128 0x00000000

# Pop Gun Mortar Reticle
"gpopgun"                          reticle2             0    64    32    13   128   128 0x00000000
"gpopgun.L0"                       reticle2             0    79     9     5   128   128 0x00000000
"gpopgun.R0"                       reticle2            23    79     9     5   128   128 0x00000000
"gpopgun.L1"                       reticle2             0    86     6     5   128   128 0x00000000
"gpopgun.R1"                       reticle2            26    86     6     5   128   128 0x00000000

# Manual Detonation Mortar Reticle
"gmdmgun.0"                        reticle2            32    64    32    13   128   128 0x00000000
"gmdmgun.1"                        reticle2            32    77    32    13   128   128 0x00000000
"gmdmgun.L0"                       reticle2            32    93     8     3   128   128 0x00000000
"gmdmgun.R0"                       reticle2            41    93     8     3   128   128 0x00000000
"gmdmgun.L1"                       reticle2            50    93     5     3   128   128 0x00000000
"gmdmgun.R1"                       reticle2            56    93     5     3   128   128 0x00000000

# Splinter Bomb Reticle
"gsplint"                          reticle2            64    64    32    13   128   128 0x00000000
"gsplint.L0"                       reticle2            64    81     7     5   128   128 0x00000000
"gsplint.R0"                       reticle2            89    81     7     5   128   128 0x00000000
"gsplint.L1"                       reticle2            64    88     5     5   128   128 0x00000000
"gsplint.R1"                       reticle2            91    88     5     5   128   128 0x00000000

# Targeting Reticle Gauge
"grnbar"                           reticle2            97    64     5    54   128   128 0x00000000
"yelbar"                           reticle2           103    64     5    54   128   128 0x00000000
"redbar"                           reticle2           109    64     5    54   128   128 0x00000000

# Objective Reticle
"object.W"                         target               0     0    64    64   128   128 0x00000000
"object.G"                         target               0     0    64    64   128   128 0x00000004
"object.Y"                         target               0     0    64    64   128   128 0x00000005
"object.R"                         target               0     0    64    64   128   128 0x00000006
"object.B"                         target               0     0    64    64   128   128 0x00000007

# Selection Reticle
"select.W"                         target              64     0    64    64   128   128 0x00000000
"select.G"                         target              64     0    64    64   128   128 0x00000004
"select.Y"                         target              64     0    64    64   128   128 0x00000005
"select.R"                         target              64     0    64    64   128   128 0x00000006
"select.B"                         target              64     0    64    64   128   128 0x00000007

# Targeting Reticle
"target.W"                         target               0    64    64    64   128   128 0x00000000
"target.G"                         target               0    64    64    64   128   128 0x00000004
"target.Y"                         target               0    64    64    64   128   128 0x00000005
"target.R"                         target               0    64    64    64   128   128 0x00000006
"target.B"                         target               0    64    64    64   128   128 0x00000007

# Ground Reticle
"ground.W"                         groundtarget        64    64    64    64   128   128 0x00000000
"ground.G"                         groundtarget        64    64    64    64   128   128 0x00000004
"ground.Y"                         groundtarget        64    64    64    64   128   128 0x00000005
"ground.R"                         groundtarget        64    64    64    64   128   128 0x00000006
"ground.B"                         groundtarget        64    64    64    64   128   128 0x00000007

# Down Caret
"caret_d.W"                        target              25     0    15    19   128   128 0x00000000
"caret_d.G"                        target              25     0    15    19   128   128 0x00000004
"caret_d.Y"                        target              25     0    15    19   128   128 0x00000005
"caret_d.R"                        target              25     0    15    19   128   128 0x00000006
"caret_d.B"                        target              25     0    15    19   128   128 0x00000007

# Right Caret
"caret_r.W"                        target               0    25    19    15   128   128 0x00000000
"caret_r.G"                        target               0    25    19    15   128   128 0x00000004
"caret_r.Y"                        target               0    25    19    15   128   128 0x00000005
"caret_r.R"                        target               0    25    19    15   128   128 0x00000006
"caret_r.B"                        target               0    25    19    15   128   128 0x00000007

# Left Caret
"caret_l.W"                        target              45    25    19    15   128   128 0x00000000
"caret_l.G"                        target              45    25    19    15   128   128 0x00000004
"caret_l.Y"                        target              45    25    19    15   128   128 0x00000005
"caret_l.R"                        target              45    25    19    15   128   128 0x00000006
"caret_l.B"                        target              45    25    19    15   128   128 0x00000007

# Up Caret
"caret_u.W"                        target              25    45    15    19   128   128 0x00000000
"caret_u.G"                        target              25    45    15    19   128   128 0x00000004
"caret_u.Y"                        target              25    45    15    19   128   128 0x00000005
"caret_u.R"                        target              25    45    15    19   128   128 0x00000006
"caret_u.B"                        target              25    45    15    19   128   128 0x00000007

# Terrain Editor Icons
"edit_eye.0"                       terredit             0     0    16    16   128   128 0x00000000
"edit_eye.1"                       terredit            64     0    16    16   128   128 0x00000000
"edit_rot.0"                       terredit             0    16    16    16   128   128 0x00000000
"edit_rot.1"                       terredit            64    16    16    16   128   128 0x00000000
"edit_v.0"                         terredit             0    32    16    16   128   128 0x00000000
"edit_v.1"                         terredit            64    32    16    16   128   128 0x00000000
"edit_h.0"                         terredit             0    48    16    16   128   128 0x00000000
"edit_h.1"                         terredit            64    48    16    16   128   128 0x00000000
"edit_pnt.0"                       terredit             0    64    16    16   128   128 0x00000000
"edit_pnt.1"                       terredit            64    64    16    16   128   128 0x00000000
"edit_mag.0"                       terredit            16     0    16    16   128   128 0x00000000
"edit_mag.1"                       terredit            80     0    16    16   128   128 0x00000000
"edit_sol.0"                       terredit            16    16    16    16   128   128 0x00000000
"edit_sol.1"                       terredit            80    16    16    16   128   128 0x00000000
"edit_cap.0"                       terredit            16    32    16    16   128   128 0x00000000
"edit_cap.1"                       terredit            80    32    16    16   128   128 0x00000000
"edit_dia.0"                       terredit            16    48    16    16   128   128 0x00000000
"edit_dia.1"                       terredit            80    48    16    16   128   128 0x00000000
"edit_var.0"                       terredit            16    64    16    16   128   128 0x00000000
"edit_var.1"                       terredit            80    64    16    16   128   128 0x00000000
"edit_ady.0"                       terredit            32     0    16    16   128   128 0x00000000
"edit_ady.1"                       terredit            96     0    16    16   128   128 0x00000000
"edit_flt.0"                       terredit            32    16    16    16   128   128 0x00000000
"edit_flt.1"                       terredit            96    16    16    16   128   128 0x00000000
"edit_pt.0"                        terredit            32    32    16    16   128   128 0x00000000
"edit_pt.1"                        terredit            96    32    16    16   128   128 0x00000000
"edit_x.0"                         terredit            32    48    16    16   128   128 0x00000000
"edit_x.1"                         terredit            96    48    16    16   128   128 0x00000000
"edit_y.0"                         terredit            32    64    16    16   128   128 0x00000000
"edit_y.1"                         terredit            96    64    16    16   128   128 0x00000000
"edit_inc.0"                       terredit            32    80    16    16   128   128 0x00000000
"edit_inc.1"                       terredit            96    80    16    16   128   128 0x00000000
"edit_adb.0"                       terredit            48     0    16    16   128   128 0x00000000
"edit_adb.1"                       terredit           112     0    16    16   128   128 0x00000000
"edit_bel.0"                       terredit            48    16    16    16   128   128 0x00000000
"edit_bel.1"                       terredit           112    16    16    16   128   128 0x00000000
"edit_drp.0"                       terredit            48    32    16    16   128   128 0x00000000
"edit_drp.1"                       terredit           112    32    16    16   128   128 0x00000000
"edit_z.0"                         terredit            48    48    16    16   128   128 0x00000000
"edit_z.1"                         terredit           112    48    16    16   128   128 0x00000000
"edit_std.0"                       terredit            48    64    16    16   128   128 0x00000000
"edit_std.1"                       terredit           112    64    16    16   128   128 0x00000000
"edit_blr.0"                       terredit            48    80    16    16   128   128 0x00000000
"edit_blr.1"                       terredit           112    80    16    16   128   128 0x00000000
"edit_arw"                         terredit             0    80    16    16   128   128 0x00000000
"edit_but.0"                       terredit             0   108    20    20   128   128 0x00000000
"edit_but.1"                       terredit            20   108    20    20   128   128 0x00000000

# Bullet Ground Hit
"xbulg.0"                          bullthit             0     0    32    32   128   128 0x00000010
"xbulg.1"                          bullthit            32     0    32    32   128   128 0x00000010
"xbulg.2"                          bullthit            64     0    32    32   128   128 0x00000010
"xbulg.3"                          bullthit            96     0    32    32   128   128 0x00000010
"xbulg.4"                          bullthit             0    32    32    32   128   128 0x00000010
"xbulg.5"                          bullthit            32    32    32    32   128   128 0x00000010
"xbulg.6"                          bullthit            64    32    32    32   128   128 0x00000010
"xbulg.7"                          bullthit            96    32    32    32   128   128 0x00000010
"xbulg.8"                          bullthit             0    64    32    32   128   128 0x00000010
"xbulg.9"                          bullthit            32    64    32    32   128   128 0x00000010

# Bullet Object Hit
"xbulh.0"                          bullthit            64    64    32    32   128   128 0x00000010
"xbulh.1"                          bullthit            96    64    32    32   128   128 0x00000010
"xbulh.2"                          bullthit             0    96    32    32   128   128 0x00000010
"xbulh.3"                          bullthit            32    96    32    32   128   128 0x00000010
"xbulh.4"                          bullthit            64    96    32    32   128   128 0x00000010

# Secondary Explosion
"xsecx.0"                          xsecxpl              0     0    64    64   256   512 0x00000000
"xsecx.1"                          xsecxpl             64     0    64    64   256   512 0x00000000
"xsecx.2"                          xsecxpl            128     0    64    64   256   512 0x00000000
"xsecx.3"                          xsecxpl            192     0    64    64   256   512 0x00000000
"xsecx.4"                          xsecxpl              0    64    64    64   256   512 0x00000000
"xsecx.5"                          xsecxpl             64    64    64    64   256   512 0x00000000
"xsecx.6"                          xsecxpl            128    64    64    64   256   512 0x00000000
"xsecx.7"                          xsecxpl            192    64    64    64   256   512 0x00000000
"xsecx.8"                          xsecxpl              0   128    64    64   256   512 0x00000000
"xsecx.9"                          xsecxpl             64   128    64    64   256   512 0x00000000
"xsecx.10"                         xsecxpl            128   128    64    64   256   512 0x00000000
"xsecx.11"                         xsecxpl            192   128    64    64   256   512 0x00000000
"xsecx.12"                         xsecxpl              0   192    64    64   256   512 0x00000000
"xsecx.13"                         xsecxpl             64   192    64    64   256   512 0x00000000
"xsecx.14"                         xsecxpl            128   192    64    64   256   512 0x00000000
"xsecx.15"                         xsecxpl            192   192    64    64   256   512 0x00000000
"xsecx.16"                         xsecxpl              0   256    64    64   256   512 0x00000000
"xsecx.17"                         xsecxpl             64   256    64    64   256   512 0x00000000
"xsecx.18"                         xsecxpl            128   256    64    64   256   512 0x00000000
"xsecx.19"                         xsecxpl            192   256    64    64   256   512 0x00000000
"xsecx.20"                         xsecxpl              0   320    64    64   256   512 0x00000000
"xsecx.21"                         xsecxpl             64   320    64    64   256   512 0x00000000
"xsecx.22"                         xsecxpl            128   320    64    64   256   512 0x00000000
"xsecx.23"                         xsecxpl            192   320    64    64   256   512 0x00000000
"xsecx.24"                         xsecxpl              0   384    64    64   256   512 0x00000000
"xsecx.25"                         xsecxpl             64   384    64    64   256   512 0x00000000
"xsecx.26"                         xsecxpl            128   384    64    64   256   512 0x00000000
"xsecx.27"                         xsecxpl            192   384    64    64   256   512 0x00000000
"xsecx.28"                         xsecxpl              0   448    64    64   256   512 0x00000000
"xsecx.29"                         xsecxpl             64   448    64    64   256   512 0x00000000
"xsecx.30"                         xsecxpl            128   448    64    64   256   512 0x00000000
"xsecx.31"                         xsecxpl            192   448    64    64   256   512 0x00000000

# Vehicle Explosion
"xcarx.0"                          xcarxpl              0     0    64    64   256   512 0x00000000
"xcarx.1"                          xcarxpl             64     0    64    64   256   512 0x00000000
"xcarx.2"                          xcarxpl            128     0    64    64   256   512 0x00000000
"xcarx.3"                          xcarxpl            192     0    64    64   256   512 0x00000000
"xcarx.4"                          xcarxpl              0    64    64    64   256   512 0x00000000
"xcarx.5"                          xcarxpl             64    64    64    64   256   512 0x00000000
"xcarx.6"                          xcarxpl            128    64    64    64   256   512 0x00000000
"xcarx.7"                          xcarxpl            192    64    64    64   256   512 0x00000000
"xcarx.8"                          xcarxpl              0   128    64    64   256   512 0x00000000
"xcarx.9"                          xcarxpl             64   128    64    64   256   512 0x00000000
"xcarx.10"                         xcarxpl            128   128    64    64   256   512 0x00000000
"xcarx.11"                         xcarxpl            192   128    64    64   256   512 0x00000000
"xcarx.12"                         xcarxpl              0   192    64    64   256   512 0x00000000
"xcarx.13"                         xcarxpl             64   192    64    64   256   512 0x00000000
"xcarx.14"                         xcarxpl            128   192    64    64   256   512 0x00000000
"xcarx.15"                         xcarxpl            192   192    64    64   256   512 0x00000000
"xcarx.16"                         xcarxpl              0   256    64    64   256   512 0x00000000
"xcarx.17"                         xcarxpl             64   256    64    64   256   512 0x00000000
"xcarx.18"                         xcarxpl            128   256    64    64   256   512 0x00000000
"xcarx.19"                         xcarxpl            192   256    64    64   256   512 0x00000000
"xcarx.20"                         xcarxpl              0   320    64    64   256   512 0x00000000
"xcarx.21"                         xcarxpl             64   320    64    64   256   512 0x00000000
"xcarx.22"                         xcarxpl            128   320    64    64   256   512 0x00000000
"xcarx.23"                         xcarxpl            192   320    64    64   256   512 0x00000000
"xcarx.24"                         xcarxpl              0   384    64    64   256   512 0x00000000
"xcarx.25"                         xcarxpl             64   384    64    64   256   512 0x00000000
"xcarx.26"                         xcarxpl            128   384    64    64   256   512 0x00000000
"xcarx.27"                         xcarxpl            192   384    64    64   256   512 0x00000000
"xcarx.28"                         xcarxpl              0   448    64    64   256   512 0x00000000
"xcarx.29"                         xcarxpl             64   448    64    64   256   512 0x00000000
"xcarx.30"                         xcarxpl            128   448    64    64   256   512 0x00000000
"xcarx.31"                         xcarxpl            192   448    64    64   256   512 0x00000000

# Light (White) Smoke
"lsmoke.0"                         smoke                0     0    32    32   128   128 0x00000000
"lsmoke.1"                         smoke               32     0    32    32   128   128 0x00000000
"lsmoke.2"                         smoke               64     0    32    32   128   128 0x00000000
"lsmoke.3"                         smoke               96     0    32    32   128   128 0x00000000
"lsmoke.4"                         smoke                0    32    32    32   128   128 0x00000000
"lsmoke.5"                         smoke               32    32    32    32   128   128 0x00000000
"lsmoke.6"                         smoke               64    32    32    32   128   128 0x00000000
"lsmoke.7"                         smoke               96    32    32    32   128   128 0x00000000
"lsmoke.8"                         smoke                0    64    32    32   128   128 0x00000000
"lsmoke.9"                         smoke               32    64    32    32   128   128 0x00000000
"lsmoke.10"                        smoke               64    64    32    32   128   128 0x00000000
"lsmoke.11"                        smoke               96    64    32    32   128   128 0x00000000
"lsmoke.12"                        smoke                0    96    32    32   128   128 0x00000000
"lsmoke.13"                        smoke               32    96    32    32   128   128 0x00000000
"lsmoke.14"                        smoke               64    96    32    32   128   128 0x00000000
"lsmoke.15"                        smoke               96    96    32    32   128   128 0x00000000

# Medium (Tan) Smoke
"msmoke.0"                         smoke                0     0    32    32   128   128 0x00000001
"msmoke.1"                         smoke               32     0    32    32   128   128 0x00000001
"msmoke.2"                         smoke               64     0    32    32   128   128 0x00000001
"msmoke.3"                         smoke               96     0    32    32   128   128 0x00000001
"msmoke.4"                         smoke                0    32    32    32   128   128 0x00000001
"msmoke.5"                         smoke               32    32    32    32   128   128 0x00000001
"msmoke.6"                         smoke               64    32    32    32   128   128 0x00000001
"msmoke.7"                         smoke               96    32    32    32   128   128 0x00000001
"msmoke.8"                         smoke                0    64    32    32   128   128 0x00000001
"msmoke.9"                         smoke               32    64    32    32   128   128 0x00000001
"msmoke.10"                        smoke               64    64    32    32   128   128 0x00000001
"msmoke.11"                        smoke               96    64    32    32   128   128 0x00000001
"msmoke.12"                        smoke                0    96    32    32   128   128 0x00000001
"msmoke.13"                        smoke               32    96    32    32   128   128 0x00000001
"msmoke.14"                        smoke               64    96    32    32   128   128 0x00000001
"msmoke.15"                        smoke               96    96    32    32   128   128 0x00000001

# Dark (Brown) Smoke
"dsmoke.0"                         smoke                0     0    32    32   128   128 0x00000002
"dsmoke.1"                         smoke               32     0    32    32   128   128 0x00000002
"dsmoke.2"                         smoke               64     0    32    32   128   128 0x00000002
"dsmoke.3"                         smoke               96     0    32    32   128   128 0x00000002
"dsmoke.4"                         smoke                0    32    32    32   128   128 0x00000002
"dsmoke.5"                         smoke               32    32    32    32   128   128 0x00000002
"dsmoke.6"                         smoke               64    32    32    32   128   128 0x00000002
"dsmoke.7"                         smoke               96    32    32    32   128   128 0x00000002
"dsmoke.8"                         smoke                0    64    32    32   128   128 0x00000002
"dsmoke.9"                         smoke               32    64    32    32   128   128 0x00000002
"dsmoke.10"                        smoke               64    64    32    32   128   128 0x00000002
"dsmoke.11"                        smoke               96    64    32    32   128   128 0x00000002
"dsmoke.12"                        smoke                0    96    32    32   128   128 0x00000002
"dsmoke.13"                        smoke               32    96    32    32   128   128 0x00000002
"dsmoke.14"                        smoke               64    96    32    32   128   128 0x00000002
"dsmoke.15"                        smoke               96    96    32    32   128   128 0x00000002

# Black Smoke
"bsmoke.0"                         smoke                0     0    32    32   128   128 0x00000003
"bsmoke.1"                         smoke               32     0    32    32   128   128 0x00000003
"bsmoke.2"                         smoke               64     0    32    32   128   128 0x00000003
"bsmoke.3"                         smoke               96     0    32    32   128   128 0x00000003
"bsmoke.4"                         smoke                0    32    32    32   128   128 0x00000003
"bsmoke.5"                         smoke               32    32    32    32   128   128 0x00000003
"bsmoke.6"                         smoke               64    32    32    32   128   128 0x00000003
"bsmoke.7"                         smoke               96    32    32    32   128   128 0x00000003
"bsmoke.8"                         smoke                0    64    32    32   128   128 0x00000003
"bsmoke.9"                         smoke               32    64    32    32   128   128 0x00000003
"bsmoke.10"                        smoke               64    64    32    32   128   128 0x00000003
"bsmoke.11"                        smoke               96    64    32    32   128   128 0x00000003
"bsmoke.12"                        smoke                0    96    32    32   128   128 0x00000003
"bsmoke.13"                        smoke               32    96    32    32   128   128 0x00000003
"bsmoke.14"                        smoke               64    96    32    32   128   128 0x00000003
"bsmoke.15"                        smoke               96    96    32    32   128   128 0x00000003

# Rocket Smoke
"rsmoke.0"                         smoke                0     0    32    32   128   128 0x00000009
"rsmoke.1"                         smoke               32     0    32    32   128   128 0x00000009
"rsmoke.2"                         smoke               64     0    32    32   128   128 0x00000009
"rsmoke.3"                         smoke               96     0    32    32   128   128 0x00000009
"rsmoke.4"                         smoke                0    32    32    32   128   128 0x00000009
"rsmoke.5"                         smoke               32    32    32    32   128   128 0x00000009
"rsmoke.6"                         smoke               64    32    32    32   128   128 0x00000009
"rsmoke.7"                         smoke               96    32    32    32   128   128 0x00000009
"rsmoke.8"                         smoke                0    64    32    32   128   128 0x00000009
"rsmoke.9"                         smoke               32    64    32    32   128   128 0x00000009
"rsmoke.10"                        smoke               64    64    32    32   128   128 0x00000009
"rsmoke.11"                        smoke               96    64    32    32   128   128 0x00000009
"rsmoke.12"                        smoke                0    96    32    32   128   128 0x00000009
"rsmoke.13"                        smoke               32    96    32    32   128   128 0x00000009
"rsmoke.14"                        smoke               64    96    32    32   128   128 0x00000009
"rsmoke.15"                        smoke               96    96    32    32   128   128 0x00000009

# Plasma Red Puff
"rpuff.0"                          rpuff                0     0    32    32   128   128 0x00000010
"rpuff.1"                          rpuff               32     0    32    32   128   128 0x00000010
"rpuff.2"                          rpuff               64     0    32    32   128   128 0x00000010
"rpuff.3"                          rpuff               96     0    32    32   128   128 0x00000010
"rpuff.4"                          rpuff                0    32    32    32   128   128 0x00000010
"rpuff.5"                          rpuff               32    32    32    32   128   128 0x00000010
"rpuff.6"                          rpuff               64    32    32    32   128   128 0x00000010
"rpuff.7"                          rpuff               96    32    32    32   128   128 0x00000010
"rpuff.8"                          rpuff                0    64    32    32   128   128 0x00000010
"rpuff.9"                          rpuff               32    64    32    32   128   128 0x00000010
"rpuff.10"                         rpuff               64    64    32    32   128   128 0x00000010
"rpuff.11"                         rpuff               96    64    32    32   128   128 0x00000010
"rpuff.12"                         rpuff                0    96    32    32   128   128 0x00000010
"rpuff.13"                         rpuff               32    96    32    32   128   128 0x00000010
"rpuff.14"                         rpuff               64    96    32    32   128   128 0x00000010
"rpuff.15"                         rpuff               96    96    32    32   128   128 0x00000010

# Plasma Green Puff
"gpuff.0"                          gpuff                0     0    32    32   128   128 0x00000010
"gpuff.1"                          gpuff               32     0    32    32   128   128 0x00000010
"gpuff.2"                          gpuff               64     0    32    32   128   128 0x00000010
"gpuff.3"                          gpuff               96     0    32    32   128   128 0x00000010
"gpuff.4"                          gpuff                0    32    32    32   128   128 0x00000010
"gpuff.5"                          gpuff               32    32    32    32   128   128 0x00000010
"gpuff.6"                          gpuff               64    32    32    32   128   128 0x00000010
"gpuff.7"                          gpuff               96    32    32    32   128   128 0x00000010
"gpuff.8"                          gpuff                0    64    32    32   128   128 0x00000010
"gpuff.9"                          gpuff               32    64    32    32   128   128 0x00000010
"gpuff.10"                         gpuff               64    64    32    32   128   128 0x00000010
"gpuff.11"                         gpuff               96    64    32    32   128   128 0x00000010
"gpuff.12"                         gpuff                0    96    32    32   128   128 0x00000010
"gpuff.13"                         gpuff               32    96    32    32   128   128 0x00000010
"gpuff.14"                         gpuff               64    96    32    32   128   128 0x00000010
"gpuff.15"                         gpuff               96    96    32    32   128   128 0x00000010

# Plasma Blue Puff
"bpuff.0"                          bpuff                0     0    32    32   128   128 0x00000010
"bpuff.1"                          bpuff               32     0    32    32   128   128 0x00000010
"bpuff.2"                          bpuff               64     0    32    32   128   128 0x00000010
"bpuff.3"                          bpuff               96     0    32    32   128   128 0x00000010
"bpuff.4"                          bpuff                0    32    32    32   128   128 0x00000010
"bpuff.5"                          bpuff               32    32    32    32   128   128 0x00000010
"bpuff.6"                          bpuff               64    32    32    32   128   128 0x00000010
"bpuff.7"                          bpuff               96    32    32    32   128   128 0x00000010
"bpuff.8"                          bpuff                0    64    32    32   128   128 0x00000010
"bpuff.9"                          bpuff               32    64    32    32   128   128 0x00000010
"bpuff.10"                         bpuff               64    64    32    32   128   128 0x00000010
"bpuff.11"                         bpuff               96    64    32    32   128   128 0x00000010
"bpuff.12"                         bpuff                0    96    32    32   128   128 0x00000010
"bpuff.13"                         bpuff               32    96    32    32   128   128 0x00000010
"bpuff.14"                         bpuff               64    96    32    32   128   128 0x00000010
"bpuff.15"                         bpuff               96    96    32    32   128   128 0x00000010

# Hovercraft Dust
"dust.0"                           dust                 0     0    64    64   256   512 0x0000000a
"dust.1"                           dust                64     0    64    64   256   512 0x0000000a
"dust.2"                           dust               128     0    64    64   256   512 0x0000000a
"dust.3"                           dust               192     0    64    64   256   512 0x0000000a
"dust.4"                           dust                 0    64    64    64   256   512 0x0000000a
"dust.5"                           dust                64    64    64    64   256   512 0x0000000a
"dust.6"                           dust               128    64    64    64   256   512 0x0000000a
"dust.7"                           dust               192    64    64    64   256   512 0x0000000a
"dust.8"                           dust                 0   128    64    64   256   512 0x0000000a
"dust.9"                           dust                64   128    64    64   256   512 0x0000000a
"dust.10"                          dust               128   128    64    64   256   512 0x0000000a
"dust.11"                          dust               192   128    64    64   256   512 0x0000000a
"dust.12"                          dust                 0   192    64    64   256   512 0x0000000a
"dust.13"                          dust                64   192    64    64   256   512 0x0000000a
"dust.14"                          dust               128   192    64    64   256   512 0x0000000a
"dust.15"                          dust               192   192    64    64   256   512 0x0000000a
"dust.16"                          dust                 0   256    64    64   256   512 0x0000000a
"dust.17"                          dust                64   256    64    64   256   512 0x0000000a
"dust.18"                          dust               128   256    64    64   256   512 0x0000000a
"dust.19"                          dust               192   256    64    64   256   512 0x0000000a
"dust.20"                          dust                 0   320    64    64   256   512 0x0000000a
"dust.21"                          dust                64   320    64    64   256   512 0x0000000a
"dust.22"                          dust               128   320    64    64   256   512 0x0000000a
"dust.23"                          dust               192   320    64    64   256   512 0x0000000a
"dust.24"                          dust                 0   384    64    64   256   512 0x0000000a
"dust.25"                          dust                64   384    64    64   256   512 0x0000000a
"dust.26"                          dust               128   384    64    64   256   512 0x0000000a
"dust.27"                          dust               192   384    64    64   256   512 0x0000000a
"dust.28"                          dust                 0   448    64    64   256   512 0x0000000a
"dust.29"                          dust                64   448    64    64   256   512 0x0000000a
"dust.30"                          dust               128   448    64    64   256   512 0x0000000a
"dust.31"                          dust               192   448    64    64   256   512 0x0000000a

# Exhaust Splash
"splash.0"                         splash               0     0    64    64   256   256 0x00000000
"splash.1"                         splash              64     0    64    64   256   256 0x00000000
"splash.2"                         splash             128     0    64    64   256   256 0x00000000
"splash.3"                         splash             192     0    64    64   256   256 0x00000000
"splash.4"                         splash               0    64    64    64   256   256 0x00000000
"splash.5"                         splash              64    64    64    64   256   256 0x00000000
"splash.6"                         splash             128    64    64    64   256   256 0x00000000
"splash.7"                         splash             192    64    64    64   256   256 0x00000000
"splash.8"                         splash               0   128    64    64   256   256 0x00000000
"splash.9"                         splash              64   128    64    64   256   256 0x00000000
"splash.10"                        splash             128   128    64    64   256   256 0x00000000
"splash.11"                        splash             192   128    64    64   256   256 0x00000000
"splash.12"                        splash               0   192    64    64   256   256 0x00000000
"splash.13"                        splash              64   192    64    64   256   256 0x00000000
"splash.14"                        splash             128   192    64    64   256   256 0x00000000
"splash.15"                        splash             192   192    64    64   256   256 0x00000000

# Red Exhaust Flame
"exhaust_r.0"                      rflame               0     0   128    23   128   128 0x00000010
"exhaust_r.1"                      rflame               0    23   128    23   128   128 0x00000010
"exhaust_r.2"                      rflame               0    46   128    23   128   128 0x00000010
"exhaust_r.3"                      rflame               0    69   128    23   128   128 0x00000010

# Red Bullet Tracer
"bullet_r.0"                       rflame               0    96    63    16   128   128 0x00000010
"bullet_r.1"                       rflame               0   112    63    16   128   128 0x00000010

# Red Beam
"beam_r.0"                         rflame              65    96    30    32   128   128 0x00000010
"beam_r.1"                         rflame              97    96    30    32   128   128 0x00000010

# Green Exhaust Flame
"exhaust_g.0"                      gflame               0     0   128    23   128   128 0x00000010
"exhaust_g.1"                      gflame               0    23   128    23   128   128 0x00000010
"exhaust_g.2"                      gflame               0    46   128    23   128   128 0x00000010
"exhaust_g.3"                      gflame               0    69   128    23   128   128 0x00000010

# Green Bullet Tracer
"bullet_g.0"                       gflame               0    96    63    16   128   128 0x00000010
"bullet_g.1"                       gflame               0   112    63    16   128   128 0x00000010

# Green Beam
"beam_g.0"                         gflame              65    96    30    32   128   128 0x00000010
"beam_g.1"                         gflame              97    96    30    32   128   128 0x00000010

# Blue Exhaust Flame
"exhaust_b.0"                      bflame               0     0   128    23   128   128 0x00000010
"exhaust_b.1"                      bflame               0    23   128    23   128   128 0x00000010
"exhaust_b.2"                      bflame               0    46   128    23   128   128 0x00000010
"exhaust_b.3"                      bflame               0    69   128    23   128   128 0x00000010

# Blue Bullet Tracer
"bullet_b.0"                       bflame               0    96    63    16   128   128 0x00000010
"bullet_b.1"                       bflame               0   112    63    16   128   128 0x00000010

# Blue Beam
"beam_b.0"                         bflame              65    96    30    32   128   128 0x00000010
"beam_b.1"                         bflame              97    96    30    32   128   128 0x00000010

# Plasma Ball
"plasma.0"                         magballs             0     0    64    64   128   128 0x00000010
"plasma.1"                         magballs            64     0    64    64   128   128 0x00000010
"plasma.2"                         magballs             0    64    64    64   128   128 0x00000010
"plasma.3"                         magballs            64    64    64    64   128   128 0x00000010

# Particle Ember
"particle.0"                       particle             0     0    64    64   256   256 0x00000010
"particle.1"                       particle            64     0    64    64   256   256 0x00000010
"particle.2"                       particle           128     0    64    64   256   256 0x00000010
"particle.3"                       particle           192     0    64    64   256   256 0x00000010
"particle.4"                       particle             0    64    64    64   256   256 0x00000010
"particle.5"                       particle            64    64    64    64   256   256 0x00000010
"particle.6"                       particle           128    64    64    64   256   256 0x00000010
"particle.7"                       particle           192    64    64    64   256   256 0x00000010
"particle.8"                       particle             0   128    64    64   256   256 0x00000010
"particle.9"                       particle            64   128    64    64   256   256 0x00000010
"particle.10"                      particle           128   128    64    64   256   256 0x00000010
"particle.11"                      particle           192   128    64    64   256   256 0x00000010
"particle.12"                      particle             0   192    64    64   256   256 0x00000010
"particle.13"                      particle            64   192    64    64   256   256 0x00000010
"particle.14"                      particle           128   192    64    64   256   256 0x00000010
"particle.15"                      particle           192   192    64    64   256   256 0x00000010

# Explosion Ring
"xplring.0"                        xplring              0     0    64    64   256   512 0x00000000
"xplring.1"                        xplring             64     0    64    64   256   512 0x00000000
"xplring.2"                        xplring            128     0    64    64   256   512 0x00000000
"xplring.3"                        xplring            192     0    64    64   256   512 0x00000000
"xplring.4"                        xplring              0    64    64    64   256   512 0x00000000
"xplring.5"                        xplring             64    64    64    64   256   512 0x00000000
"xplring.6"                        xplring            128    64    64    64   256   512 0x00000000
"xplring.7"                        xplring            192    64    64    64   256   512 0x00000000
"xplring.8"                        xplring              0   128    64    64   256   512 0x00000000
"xplring.9"                        xplring             64   128    64    64   256   512 0x00000000
"xplring.10"                       xplring            128   128    64    64   256   512 0x00000000
"xplring.11"                       xplring            192   128    64    64   256   512 0x00000000
"xplring.12"                       xplring              0   192    64    64   256   512 0x00000000
"xplring.13"                       xplring             64   192    64    64   256   512 0x00000000
"xplring.14"                       xplring            128   192    64    64   256   512 0x00000000
"xplring.15"                       xplring            192   192    64    64   256   512 0x00000000
"xplring.16"                       xplring              0   256    64    64   256   512 0x00000000
"xplring.17"                       xplring             64   256    64    64   256   512 0x00000000
"xplring.18"                       xplring            128   256    64    64   256   512 0x00000000
"xplring.19"                       xplring            192   256    64    64   256   512 0x00000000
"xplring.20"                       xplring              0   320    64    64   256   512 0x00000000
"xplring.21"                       xplring             64   320    64    64   256   512 0x00000000
"xplring.22"                       xplring            128   320    64    64   256   512 0x00000000
"xplring.23"                       xplring            192   320    64    64   256   512 0x00000000
"xplring.24"                       xplring              0   384    64    64   256   512 0x00000000
"xplring.25"                       xplring             64   384    64    64   256   512 0x00000000
"xplring.26"                       xplring            128   384    64    64   256   512 0x00000000
"xplring.27"                       xplring            192   384    64    64   256   512 0x00000000
"xplring.28"                       xplring              0   448    64    64   256   512 0x00000000
"xplring.29"                       xplring             64   448    64    64   256   512 0x00000000
"xplring.30"                       xplring            128   448    64    64   256   512 0x00000000
"xplring.31"                       xplring            192   448    64    64   256   512 0x00000000

# Rocket Flares
"flare.0"                          flare                0     0    64    64   128   128 0x00000010
"flare.1"                          flare               64     0    64    64   128   128 0x00000010
"flare.2"                          flare                0    64    64    64   128   128 0x00000010
"flare.3"                          flare               64    64    64    64   128   128 0x00000010

# Shockwave Ring
"shockwave.0"                      shock                0     0    32    32   128   128 0x00000010
"shockwave.1"                      shock               32     0    32    32   128   128 0x00000010
"shockwave.2"                      shock               64     0    32    32   128   128 0x00000010
"shockwave.3"                      shock               96     0    32    32   128   128 0x00000010
"shockwave.4"                      shock                0    32    32    32   128   128 0x00000010
"shockwave.5"                      shock               32    32    32    32   128   128 0x00000010
"shockwave.6"                      shock               64    32    32    32   128   128 0x00000010
"shockwave.7"                      shock               96    32    32    32   128   128 0x00000010
"shockwave.8"                      shock                0    64    32    32   128   128 0x00000010
"shockwave.9"                      shock               32    64    32    32   128   128 0x00000010
"shockwave.10"                     shock               64    64    32    32   128   128 0x00000010
"shockwave.11"                     shock               96    64    32    32   128   128 0x00000010
"shockwave.12"                     shock                0    96    32    32   128   128 0x00000010
"shockwave.13"                     shock               32    96    32    32   128   128 0x00000010
"shockwave.14"                     shock               64    96    32    32   128   128 0x00000010
"shockwave.15"                     shock               96    96    32    32   128   128 0x00000010

# Lens Flare Rings
"sun.0"                            sprite_a             0     0    63    63   128   128 0x00000010
"ring.0"                           sprite_a            32    64    15    15   128   128 0x00000010
"ring.1"                           sprite_a            32    80     9     9   128   128 0x00000010
"ring.2"                           sprite_a            32    90     5     5   128   128 0x00000010
"ring.3"                           sprite_a             0    64    31    31   128   128 0x00000010
"ring.4"                           sprite_a            64     0    63    63   128   128 0x00000010

# Radar Ping Frames
"ping.0"                           sprite_a            44    88     5     5   128   128 0x00000000
"ping.1"                           sprite_a            50    88     7     7   128   128 0x00000000
"ping.2"                           sprite_a            58    88     9     9   128   128 0x00000000
"ping.3"                           sprite_a            68    88    11    11   128   128 0x00000000
"ping.4"                           sprite_a            80    86    13    13   128   128 0x00000000
"ping.5"                           sprite_a            94    85    15    15   128   128 0x00000000
"ping.6"                           sprite_a           110    84    17    17   128   128 0x00000000
"ping.7"                           sprite_a            94    64    19    19   128   128 0x00000000
"ping.8"                           sprite_a            72    64    21    21   128   128 0x00000000
"ping.9"                           sprite_a            48    64    23    23   128   128 0x00000000
"ping.10"                          sprite_a            90   102    25    25   128   128 0x00000000
"ping.11"                          sprite_a            62   100    27    27   128   128 0x00000000
"ping.12"                          sprite_a            32    98    29    29   128   128 0x00000000
"ping.13"                          sprite_a             0    96    31    31   128   128 0x00000000

# New HIRES Underlays for target weapons radar and menu

# American versions
"targetunderlay"                   HUDcombi             0     0   590   312  1024  1024 0x00000000
"menuunderlay"                     HUDcombi             0   312   386   360  1024  1024 0x00000000
"weaponunderlay"                   HUDcombi           796   780   228   164  1024  1024 0x00000000
"radarunderlay"                    HUDcombi             0   670   584   336  1024  1024 0x00000000
"ammotext"                         HUDcombi           728   144    48    22  1024  1024 0x00000000
"hulltext"                         HUDcombi           658   140    50    32  1024  1024 0x00000000
"weaponhilight"                    HUDcombi           822   752   201    20  1024  1024 0x00000000
"mapunderlay"                      HUDcombi           664   330   344   344  1024  1024 0x00000000

# Soviet versions
"stargetunderlay"                  HUDcombS             0     0   590   312  1024  1024 0x00000000
"smenuunderlay"                    HUDcombS             0   312   386   360  1024  1024 0x00000000
"sweaponunderlay"                  HUDcombS           796   780   228   164  1024  1024 0x00000000
"sradarunderlay"                   HUDcombS             0   670   584   336  1024  1024 0x00000000
"sammotext"                        HUDcombS           728   144   120    22  1024  1024 0x00000000
"shulltext"                        HUDcombS           658   140    50    32  1024  1024 0x00000000
"sweaponhilight"                   HUDcombS           822   752   201    20  1024  1024 0x00000000
"smapunderlay"                     HUDcombS           664   330   344   344  1024  1024 0x00000000

# Fury versions
"ftargetunderlay"                  HUDcombF             0     0   590   312  1024  1024 0x00000000
"fmenuunderlay"                    HUDcombF             0   312   386   360  1024  1024 0x00000000
"fweaponunderlay"                  HUDcombF           796   780   228   164  1024  1024 0x00000000
"fradarunderlay"                   HUDcombF             0   670   584   336  1024  1024 0x00000000
"fammotext"                        HUDcombF           728   144    48    22  1024  1024 0x00000000
"fhulltext"                        HUDcombF           658   140    50    32  1024  1024 0x00000000
"fweaponhilight"                   HUDcombF           822   752   201    20  1024  1024 0x00000000
"fmapunderlay"                     HUDcombF           664   330   344   344  1024  1024 0x00000000

#NEW Buttons and misc Art for iOS versions

# NAME............................ MATERIAL........ ....U ....V ....W ....H REF.W REF.H FLAGS.....

"mobileunderlay"                   HUDcombi           851   965   156    44  1024  1024 0x00000000
"button_fire"                      Hudcombi           830   96    162    78  1024  1024 0x00000000
"button_fire_2"                    Hudcombi           830   16    162    78  1024  1024 0x00000000
"button_fire_3"                    Hudcombi           830   178   162    78  1024  1024 0x00000000
"button_toggle_weapon"             Hudcombi           808   786   211    60  1024  1024 0x00000000
"button_toggle_weapon_2"           Hudcombi           808   676   211    60  1024  1024 0x00000000
"button_toggle_navcam"         	   Hudcombi           802   786   220    72  1024  1024 0x00000000
"button_toggle_nacvam_2"           Hudcombi           802   676   220    72  1024  1024 0x00000000
"button_toggle_navcam_3"           Hudcombi           802   874   220    72  1024  1024 0x00000000
"button_analog_cam"                Hudcombi           432   396   204   206  1024  1024 0x00000000
"button_analog"                    Hudcombi           336   342   62     58  1024  1024 0x00000000
"button_analog_base"               Hudcombi            40   364   270   266  1024  1024 0x00000000
"button_tap_here"                  Hudcombi           310   335   100   235  1024  1024 0x00000000
"button_area_square"               Hudcombi           675   340   320   320  1024  1024 0x00000000

# --- Campaign Reimagined additions ---
# APPEND ONLY. Sprite handles are row indices plus a fixed base, so any
# insertion above this point renumbers every sprite that follows.

# Burnt Orange Exhaust Flame (CCA) -- Campaign Reimagined
"exhaust_o.0"                      oflame               0     0   128    23   128   128 0x00000010
"exhaust_o.1"                      oflame               0    23   128    23   128   128 0x00000010
"exhaust_o.2"                      oflame               0    46   128    23   128   128 0x00000010
"exhaust_o.3"                      oflame               0    69   128    23   128   128 0x00000010

# Blood Red Exhaust Flame (Black Dog) -- Campaign Reimagined
"exhaust_bd.0"                     bdflame              0     0   128    23   128   128 0x00000010
"exhaust_bd.1"                     bdflame              0    23   128    23   128   128 0x00000010
"exhaust_bd.2"                     bdflame              0    46   128    23   128   128 0x00000010
"exhaust_bd.3"                     bdflame              0    69   128    23   128   128 0x00000010
