[DESCRIPTION]
missionName = "CR: An Unexpected Connection Coop"

[WORKSHOP]
mapType = "multiplayer"
customtags = "Coop, Campaign Reimagined"

; Shared map/script with crcampgn.ini MISSION4.
[MULTIPLAYER]
minPlayers = "2"
maxPlayers = "4"
gameType = "S"
