-- Generated by Manage-CampaignFiles.ps1 from the managed OpenShim suite.
-- Do not edit payload metadata by hand.
return {
    formatVersion = 2,
    version = "1.0.0.19",
    sha256 = "7d1f5ee8e5e740c960f4b4d0e25a1c10207266fa152736821eb3a4cce07eef2b",
    size = 2874368,
    architecture = "x86",
    payloads = {
        winmm = { source = "winmm.dll", destination = "winmm.dll", sha256 = "7d1f5ee8e5e740c960f4b4d0e25a1c10207266fa152736821eb3a4cce07eef2b", size = 2874368, version = "1.0.0.19", architecture = "x86" },
        network = { source = "openshim_net.ini.payload", destination = "net.ini", sha256 = "25853671cceaf7273ba6b43bf0fec1bf34ed0298e8c238cb6ec68a4303e99056", size = 13245 },
        patches = { source = "openshim_patches.json.payload", destination = "scripts\\patches.json", sha256 = "958479137e2baff9fa7a244f7ae85f8fe1dc27ec9f759757b922b8aa8ee5a581", size = 30338 },
        playerConfig = { source = "openshim.ini.payload", destination = "openshim.ini", sha256 = "7fadb6097437fb6c8cf6c735ff05cb4a5472e67dc6f76c82e642cfe7a0b61acd", size = 14121, overwrite = false },
    },
}
