-- Generated by Manage-CampaignFiles.ps1 from Bin/winmm.dll.
-- Do not edit the version, hash, or size by hand.
return {
    formatVersion = 1,
    version = "1.0.0.5",
    sha256 = "a79d39b5793e0a5842a54a41d65d830b544b8c9ff6232fe23de863f231e31b16",
    size = 1332224,
    architecture = "x86",
}
