-- Generated by Manage-CampaignFiles.ps1 from the managed OpenShim suite.
-- Do not edit payload metadata by hand.
return {
    formatVersion = 3,
    version = "1.0.0.34",
    sha256 = "6063190ba8c8dc4f98be079f7b9131ad4d159e49ccd74d86c189d8595adc4f8d",
    size = 124928,
    architecture = "x86",
    payloads = {
        winmm = { source = "winmm.dll", destination = "winmm.dll", sha256 = "6063190ba8c8dc4f98be079f7b9131ad4d159e49ccd74d86c189d8595adc4f8d", size = 124928, version = "1.0.0.34", architecture = "x86" },
        loader = { source = "bzloader.dll", destination = "bzloader.dll", sha256 = "15c76087f951285f8dbeec31f6c33c862a8c7c575677bb3d43de9c54a289e409", size = 44032, version = "1.0.0.34", architecture = "x86" },
        plugin = { source = "openshim.dll", destination = "plugins\\openshim.dll", sha256 = "36b4ce5089b7f08ccdeaf60d0f34dcb3205c41857c92f0acbe8dd02f26df4abc", size = 3179008, version = "1.0.0.34", architecture = "x86" },
        network = { source = "openshim_net.ini.payload", destination = "net.ini", sha256 = "b999993bfe500a4def4444ecde065147444099a1af46d17e74f006ed2620516f", size = 13554 },
        patches = { source = "openshim_patches.json.payload", destination = "scripts\\patches.json", sha256 = "84ed3d2f4337482f703ccaf3b4df27ae3fd0b8d4b69e327922cd27936b5e9f25", size = 103697 },
        playerConfig = { source = "openshim.ini.payload", destination = "openshim.ini", sha256 = "ada7072cba1b1ec0e3fce96c47b00766f5708f3357205b0090e598de5f22d977", size = 23548, overwrite = false },
        helper = { source = "bzfile_replace_helper.exe", sha256 = "9eafbb5c3e159a5a5232873b937899df4ac22cb3a72f80795e54aa5268c0578b", size = 271360 },
    },
}
